# Generated by Django 4.2.1 on 2023-10-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_candidate_candidate_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_votes', to='myapp.candidate'),
        ),
    ]
